#!/usr/bin/env python3
"""Build the homepage hero mark partial from the settled brand mark.

Source: static/images/brand/hai-mark.svg, a copy of
/Users/david/Documents/Fawkes/Media and Outreach/Branding/HAI_Mark_Final_2026-09-26/HAI_Mark_Responsive_transparent.svg
(the two-turn Morse spiral; gold and lavender each spell FOUNDATION).

Output: layouts/partials/hero-mark.html, an inline SVG holding only the
full-size drawing (tier k0). Each dot and dash gets a CSS delay so the
mark assembles once on arrival: the lavender line from the tail inward,
the gold line from the center outward, the two passing each other.
No JavaScript; with reduced motion the mark simply appears whole.

Run from the repository root: python3 scripts/brand/build_hero_mark.py
"""
import math
import re
from pathlib import Path

SRC = Path("static/images/brand/hai-mark.svg")
OUT = Path("layouts/partials/hero-mark.html")
GOLD, LAV = "#C8964E", "#8B9DBF"
SPAN = 2.2  # seconds from first mark to last mark starting


def ease_in_out(t):
    return 0.5 - 0.5 * math.cos(math.pi * t)


def main():
    src = SRC.read_text()
    view_box = re.search(r'viewBox="([^"]+)"', src).group(1)
    k0 = re.search(r'<g class="k0">(.*?)</g>', src, re.S).group(1)
    els = re.findall(r"<(?:circle|path)[^>]*/>", k0)
    gold = [e for e in els if GOLD in e]
    lav = [e for e in els if LAV in e]
    assert len(gold) + len(lav) == len(els), "unexpected colour in mark"
    out = []
    # File order runs tail to center for both lines.
    for i, e in enumerate(lav):  # lavender reads from the tail inward
        d = SPAN * ease_in_out(i / max(1, len(lav) - 1))
        out.append(e.replace("/>", f' class="hm-l" style="--d:{d:.3f}s"/>', 1))
    n = len(gold)
    for i, e in enumerate(gold):  # gold reads from the center outward
        d = SPAN * ease_in_out((n - 1 - i) / max(1, n - 1))
        out.append(e.replace("/>", f' class="hm-g" style="--d:{d:.3f}s"/>', 1))
    svg = (
        "{{/* Generated by scripts/brand/build_hero_mark.py from static/images/brand/hai-mark.svg. Do not edit by hand. */}}\n"
        f'<svg class="hero-mark-svg" xmlns="http://www.w3.org/2000/svg" viewBox="{view_box}" '
        'role="img" aria-labelledby="heroMarkTitle">'
        '<title id="heroMarkTitle">Humanity and AI</title>'
        + "".join(out)
        + "</svg>\n"
    )
    OUT.write_text(svg)
    print(f"wrote {OUT}: {len(lav)} lavender, {len(gold)} gold, {len(svg)} bytes")


if __name__ == "__main__":
    main()
